name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_call:

permissions: write-all
  
jobs:
  Python:
    name: core / Python ${{ matrix.ver }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ver: ['3.12']

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

    - name: Set up Python
      uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
      with:
        python-version: ${{ matrix.ver }}
      env:
        PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"

    - name: Install Python ${{ matrix.ver }} dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install tox numpy mutmut

    - name: Execute Python tests
      run: | 
        timeout 4h mutmut run --no-progress
        mutmut results
    - name: Upload mutmut cache as artifact
      uses: actions/upload-artifact@v3
      with:
        name: mutmut-cache-${{ matrix.ver }}
        path: .mutmut-cache
